package com.example.fontsizecontroller.model

/**
 * Tập chuỗi đa ngôn ngữ (Localization) cho FontM.
 * Hỗ trợ chuyển đổi tức thì giữa Tiếng Việt (VI) và Tiếng Anh (EN) trong Jetpack Compose.
 */
data class AppStrings(
    // Common & Navigation
    val appTitle: String,
    val appSubtitle: String,
    val tabFontSize: String,
    val tabEyeTest: String,
    val tabFontGallery: String,
    val tabAccessibility: String,
    val btnCancel: String,
    val btnConfirm: String,
    val btnApply: String,
    val btnApplying: String,
    val btnClose: String,
    val btnBack: String,

    // Screen: FontSizeScreen
    val currentFontCardTitle: String,
    val currentFontVerifiedBadge: String,
    val fontPreviewTitle: String,
    val fontPreviewSampleText: String,
    val fontPresetsTitle: String,
    val customSliderTitle: String,
    val customSliderSubtitle: String,
    val btnApplyFontSize: String,
    val btnResetDefault: String,
    val resetDialogTitle: String,
    val resetDialogMessage: String,
    val presetSmall: String,
    val presetDefault: String,
    val presetLarge: String,
    val presetExtraLarge: String,
    val labelCustom: String,

    // Screen: EyeTestScreen
    val eyeTestTitle: String,
    val eyeTestSubtitle: String,
    val eyeTestStepPrefix: String,
    val eyeTestCompletedTitle: String,
    val eyeTestCompletedDesc: String,
    val eyeTestRecommendedBadge: String,
    val eyeTestBtnApply: String,
    val eyeTestBtnRetest: String,
    val eyeTestBtnNext: String,
    val eyeTestBtnFinish: String,

    // Screen: FontGalleryScreen
    val fontGalleryTitle: String,
    val fontGallerySubtitle: String,
    val fontCategoryAll: String,
    val fontCategoryModern: String,
    val fontCategorySerif: String,
    val fontCategoryHandwriting: String,
    val fontCategoryMonospace: String,
    val fontInstalledBadge: String,
    val fontNotAvailableBadge: String,
    val fontPreviewExpand: String,
    val fontPreviewCollapse: String,
    val fontSimulatedAppsTitle: String,
    val fontSimZaloSms: String,
    val fontSimNews: String,
    val fontSimContacts: String,

    // Screen: AccessibilityScreen
    val accessibilityTitle: String,
    val accessibilitySubtitle: String,
    val readingModeTitle: String,
    val readingModeStandard: String,
    val readingModeStandardDesc: String,
    val readingModeWarm: String,
    val readingModeWarmDesc: String,
    val readingModeHighContrast: String,
    val readingModeHighContrastDesc: String,
    val boldTextTitle: String,
    val boldTextSubtitle: String,
    val recommendationTitle: String,
    val recoYoung: String,
    val recoAdult: String,
    val recoElderly: String,

    // Screen: Settings & Help
    val settingsTitle: String,
    val settingsSubtitle: String,
    val sectionLanguage: String,
    val sectionTheme: String,
    val sectionFamilyProfiles: String,
    val sectionOemGuidance: String,
    val sectionAbout: String,
    val profileMyself: String,
    val profileParents: String,
    val profileGrandparents: String,
    val btnOpenDisplaySettings: String,
    val oemSamsungTitle: String,
    val oemSamsungGuide: String,
    val oemXiaomiTitle: String,
    val oemXiaomiGuide: String,
    val oemOppoTitle: String,
    val oemOppoGuide: String,
    val aboutAppVersion: String,
    val aboutPrivacyCommitment: String,

    // Quick Settings Tile
    val tileLabel: String,
    val tileDesc: String
)

object LocalizedStrings {
    val vietnamese = AppStrings(
        appTitle = "FontM",
        appSubtitle = "Thay đổi phông chữ & cỡ chữ dễ dàng",
        tabFontSize = "Cỡ Chữ",
        tabEyeTest = "Đo Mắt",
        tabFontGallery = "Kiểu Chữ",
        tabAccessibility = "Trợ Năng",
        btnCancel = "Hủy bỏ",
        btnConfirm = "Xác nhận",
        btnApply = "Áp dụng",
        btnApplying = "Đang ghi...",
        btnClose = "Đóng",
        btnBack = "Quay lại",

        currentFontCardTitle = "Cỡ Chữ Hiện Tại",
        currentFontVerifiedBadge = "Đã xác thực trên Android",
        fontPreviewTitle = "Xem Trước Văn Bản",
        fontPreviewSampleText = "Sông Hồng đỏ nặng phù sa, mang theo tình cảm thiết tha của người dân đồng bằng Bắc Bộ qua bao đời nay.",
        fontPresetsTitle = "Mức Cỡ Chữ Có Sẵn",
        customSliderTitle = "Tự Chọn Cỡ Chữ Theo Ý Muốn",
        customSliderSubtitle = "Tự do chỉnh từ 0.80x đến 2.00x",
        btnApplyFontSize = "Áp Dụng Cỡ Chữ Này",
        btnResetDefault = "Đặt Lại Mặc Định (1.00x)",
        resetDialogTitle = "Khôi phục cỡ chữ chuẩn?",
        resetDialogMessage = "Bạn có chắc chắn muốn đưa cỡ chữ hệ thống về mức mặc định 1.00x ban đầu của máy không?",
        presetSmall = "Cỡ Nhỏ",
        presetDefault = "Mặc Định",
        presetLarge = "Cỡ Lớn",
        presetExtraLarge = "Cỡ Rất Lớn",
        labelCustom = "Tùy Chỉnh",

        eyeTestTitle = "Kiểm Tra Thị Lực",
        eyeTestSubtitle = "Tìm kích thước chữ đọc thoải mái nhất cho mắt bạn",
        eyeTestStepPrefix = "Bước",
        eyeTestCompletedTitle = "Đã Hoành Thành Đo Mắt",
        eyeTestCompletedDesc = "Cỡ chữ đề xuất tốt nhất cho thị lực của bạn là:",
        eyeTestRecommendedBadge = "Khuyên dùng cho bạn",
        eyeTestBtnApply = "Áp Dụng Cỡ Chữ Này Cho Máy",
        eyeTestBtnRetest = "Đo Lại Từ Đầu",
        eyeTestBtnNext = "Tiếp tục bước kế",
        eyeTestBtnFinish = "Xem kết quả & Áp dụng",

        fontGalleryTitle = "Thư Viện Kiểu Chữ",
        fontGallerySubtitle = "Các phông chữ thực tế có sẵn trên máy của bạn",
        fontCategoryAll = "Tất cả",
        fontCategoryModern = "Hiện đại",
        fontCategorySerif = "Có chân",
        fontCategoryHandwriting = "Viết tay",
        fontCategoryMonospace = "Máy tính",
        fontInstalledBadge = "Đã có trên máy",
        fontNotAvailableBadge = "Chưa cài",
        fontPreviewExpand = "Xem thử kiểu chữ này",
        fontPreviewCollapse = "Thu gọn xem thử",
        fontSimulatedAppsTitle = "Mô Phỏng Ứng Dụng Đời Thực",
        fontSimZaloSms = "Tin nhắn SMS",
        fontSimNews = "Báo điện tử",
        fontSimContacts = "Danh bạ điện thoại",

        accessibilityTitle = "Bộ Trợ Năng Đọc Sách",
        accessibilitySubtitle = "Màu sắc & độ tương phản bảo vệ thị lực khi đọc lâu",
        readingModeTitle = "Chế Độ Đọc Thị Lực",
        readingModeStandard = "Chuẩn Mặc Định",
        readingModeStandardDesc = "Theo chế độ sáng / tối của máy",
        readingModeWarm = "Sách Vàng Ấm",
        readingModeWarmDesc = "Dịu mắt, lọc ánh sáng xanh ban đêm",
        readingModeHighContrast = "Độ Tương Phản Cao",
        readingModeHighContrastDesc = "Nền đen chữ vàng sáng, đạt chuẩn WCAG AAA cho mắt yếu",
        boldTextTitle = "Mô Phỏng Chữ Đậm",
        boldTextSubtitle = "Làm nổi bật nét chữ, dễ đọc khi mắt mờ",
        recommendationTitle = "Gợi Ý Cỡ Chữ Theo Nhu Cầu",
        recoYoung = "Thị lực tốt / Đọc nhanh",
        recoAdult = "Mắt cận / Làm việc nhiều với màn hình",
        recoElderly = "Người lớn tuổi / Mắt yếu",

        settingsTitle = "Cài Đặt & Trợ Giúp",
        settingsSubtitle = "Tùy chỉnh hệ thống & Hướng dẫn cài đặt theo dòng máy",
        sectionLanguage = "Ngôn Ngữ Ứng Dụng",
        sectionTheme = "Giao Diện (Chế độ tối)",
        sectionFamilyProfiles = "Hồ Sơ Cỡ Chữ Gia Đình",
        sectionOemGuidance = "Hướng Dẫn Cài Đặt Theo Hãng Máy",
        sectionAbout = "Thông Tin Ứng Dụng",
        profileMyself = "Cá Nhân (1.00x)",
        profileParents = "Bố Mẹ (1.15x)",
        profileGrandparents = "Ông Bà (1.30x)",
        btnOpenDisplaySettings = "Mở Cài Đặt Màn Hình Của Máy ↗",
        oemSamsungTitle = "Samsung (One UI)",
        oemSamsungGuide = "Vào Cài đặt ➔ Màn hình ➔ Cỡ phông bạt và kiểu phông để chỉnh thêm kiểu phông của máy.",
        oemXiaomiTitle = "Xiaomi / Redmi (MIUI / HyperOS)",
        oemXiaomiGuide = "Vào Cài đặt ➔ Ứng dụng ➔ Quyền riêng tư ➔ Bật quyền Sửa đổi cài đặt hệ thống cho FontM.",
        oemOppoTitle = "OPPO / Realme (ColorOS)",
        oemOppoGuide = "Vào Cài đặt ➔ Màn hình & Độ sáng ➔ Phông chữ và kích thước hiển thị.",
        aboutAppVersion = "Phiên bản: 1.0.0 (Native Kotlin)",
        aboutPrivacyCommitment = "Cam kết bảo mật: Ứng dụng không thu thập bất kỳ dữ liệu cá nhân hay lịch sử thao tác nào.",

        tileLabel = "Cỡ Chữ FontM",
        tileDesc = "Chỉnh nhanh cỡ chữ trên thanh thông báo"
    )

    val english = AppStrings(
        appTitle = "FontM",
        appSubtitle = "Effortlessly adjust system font scale & styles",
        tabFontSize = "Font Size",
        tabEyeTest = "Vision Test",
        tabFontGallery = "Font Styles",
        tabAccessibility = "Accessibility",
        btnCancel = "Cancel",
        btnConfirm = "Confirm",
        btnApply = "Apply",
        btnApplying = "Applying...",
        btnClose = "Close",
        btnBack = "Back",

        currentFontCardTitle = "Current Font Scale",
        currentFontVerifiedBadge = "Verified on Android System",
        fontPreviewTitle = "Live Text Preview",
        fontPreviewSampleText = "The quick brown fox jumps over the lazy dog. Clear reading brings joy and comfort to everyone every day.",
        fontPresetsTitle = "Preset Font Scales",
        customSliderTitle = "Custom Font Scale",
        customSliderSubtitle = "Freely adjust from 0.80x to 2.00x",
        btnApplyFontSize = "Apply This Font Scale",
        btnResetDefault = "Reset to Default (1.00x)",
        resetDialogTitle = "Reset to Default Scale?",
        resetDialogMessage = "Are you sure you want to restore the system font scale back to the default 1.00x level?",
        presetSmall = "Small",
        presetDefault = "Default",
        presetLarge = "Large",
        presetExtraLarge = "Extra Large",
        labelCustom = "Custom",

        eyeTestTitle = "Smart Vision Test",
        eyeTestSubtitle = "Find the most comfortable reading size for your eyes",
        eyeTestStepPrefix = "Step",
        eyeTestCompletedTitle = "Vision Test Completed",
        eyeTestCompletedDesc = "The most comfortable font scale for your eyes is:",
        eyeTestRecommendedBadge = "Recommended for you",
        eyeTestBtnApply = "Apply This Scale to System",
        eyeTestBtnRetest = "Retake Test",
        eyeTestBtnNext = "Continue to next step",
        eyeTestBtnFinish = "View Result & Apply",

        fontGalleryTitle = "Font Style Gallery",
        fontGallerySubtitle = "Real typography fonts available on your device",
        fontCategoryAll = "All",
        fontCategoryModern = "Modern",
        fontCategorySerif = "Serif",
        fontCategoryHandwriting = "Handwriting",
        fontCategoryMonospace = "Monospace",
        fontInstalledBadge = "Installed",
        fontNotAvailableBadge = "Not available",
        fontPreviewExpand = "Preview this font style",
        fontPreviewCollapse = "Collapse preview",
        fontSimulatedAppsTitle = "Real-world App Simulation",
        fontSimZaloSms = "SMS Messaging",
        fontSimNews = "News Article",
        fontSimContacts = "Phone Contacts",

        accessibilityTitle = "Reading Accessibility",
        accessibilitySubtitle = "Eye protection colors & high contrast presets",
        readingModeTitle = "Reading Color Presets",
        readingModeStandard = "Standard Theme",
        readingModeStandardDesc = "Follows system light / dark mode",
        readingModeWarm = "Warm Book (Sepia)",
        readingModeWarmDesc = "Gentle on the eyes, filters night blue light",
        readingModeHighContrast = "High Contrast",
        readingModeHighContrastDesc = "Deep black with yellow text, WCAG AAA certified for low vision",
        boldTextTitle = "Simulate Bold Text",
        boldTextSubtitle = "Emphasize glyph outlines for easier reading",
        recommendationTitle = "Recommended Scales by Need",
        recoYoung = "Normal vision / Fast readers",
        recoAdult = "Near-sighted / Heavy screen users",
        recoElderly = "Seniors / Low vision eyes",

        settingsTitle = "Settings & Help",
        settingsSubtitle = "System adjustments & OEM manufacturer guidelines",
        sectionLanguage = "App Language",
        sectionTheme = "Dark Theme",
        sectionFamilyProfiles = "Family Font Profiles",
        sectionOemGuidance = "Manufacturer Setup Guide",
        sectionAbout = "About FontM",
        profileMyself = "Myself (1.00x)",
        profileParents = "Parents (1.15x)",
        profileGrandparents = "Grandparents (1.30x)",
        btnOpenDisplaySettings = "Open System Display Settings ↗",
        oemSamsungTitle = "Samsung (One UI)",
        oemSamsungGuide = "Go to Settings ➔ Display ➔ Font size and style to choose additional system fonts.",
        oemXiaomiTitle = "Xiaomi / Redmi (MIUI / HyperOS)",
        oemXiaomiGuide = "Go to Settings ➔ Apps ➔ Permissions ➔ Enable Modify System Settings for FontM.",
        oemOppoTitle = "OPPO / Realme (ColorOS)",
        oemOppoGuide = "Go to Settings ➔ Display & Brightness ➔ Font & display size.",
        aboutAppVersion = "Version: 1.0.0 (Native Kotlin)",
        aboutPrivacyCommitment = "Privacy Guarantee: FontM collects zero personal data or browsing activity.",

        tileLabel = "FontM Scale",
        tileDesc = "Quickly adjust font scale from notification panel"
    )

    fun get(language: AppLanguage): AppStrings = when (language) {
        AppLanguage.VI -> vietnamese
        AppLanguage.EN -> english
    }
}
